name: Kong Deck Workflow

on:
  push:
    branches:
      - main
    paths:
      - "openapi/**/*"
  pull_request:
    paths:
      - "openapi/**/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Lint OAS spec
        uses: docker://kong/inso
        with:
          args: lint spec openapi/openapi.yaml

  convert-deck:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Convert OAS to deck YAML
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tmp \
            --user $(id -u):$(id -g) \
            -w /tmp \
            kong/deck file openapi2kong -s openapi/openapi.yaml -o /tmp/deck.yaml
      - name: Upload deck.yaml artifact
        uses: actions/upload-artifact@v4
        with:
          name: deck
          path: deck.yaml

  add-plugins-deck:
    runs-on: ubuntu-latest
    needs: convert-deck
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: deck
      - name: Merge plugins to deck YAML
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tmp \
            --user $(id -u):$(id -g) \
            -w /tmp \
            kong/deck file add-plugins -s deck.yaml \
            kong/plugins/key-auth.yaml kong/plugins/prometheus.yaml kong/plugins/proxy-cache.yaml kong/plugins/rate-limiting-advanced.yaml \
            -o add-plugins-deck.yaml
      - name: Upload merged-deck.yaml artifact
        uses: actions/upload-artifact@v4
        with:
          name: add-plugins-deck
          path: add-plugins-deck.yaml
          
  add-consumers-deck:
    runs-on: ubuntu-latest
    needs: add-plugins-deck
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: add-plugins-deck
      - name: Merge plugins to deck YAML
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tmp \
            --user $(id -u):$(id -g) \
            -w /tmp \
            kong/deck file merge add-plugins-deck.yaml kong/consumers/consumer.yaml -o merged-deck.yaml
      - name: Upload merged-deck.yaml artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged-deck
          path: merged-deck.yaml
          
  valid-deck:
    runs-on: ubuntu-latest
    needs: add-consumers-deck
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: merged-deck
      - name: Validate merged-deck.yaml
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/tmp \
            -w /tmp \
            -e DECK_KONNECT_ADDR=${{ vars.KONNECT_ADDR }} \
            -e DECK_TLS_SKIP_VERIFY=${{ vars.TLS_SKIP_VERIFY }} \
            -e DECK_KONNECT_TOKEN=${{ secrets.KONNECT_TOKEN }} \
            -e DECK_KONNECT_CONTROL_PLANE_NAME=${{ vars.KONNECT_CONTROL_PLANE_NAME }} \
            kong/deck gateway validate merged-deck.yaml

  diff-deck:
    runs-on: ubuntu-latest
    needs: valid-deck
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: merged-deck
      - name: Diff merged-deck.yaml and Gateway
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/tmp \
            -w /tmp \
            -e DECK_KONNECT_ADDR=${{ vars.KONNECT_ADDR }} \
            -e DECK_TLS_SKIP_VERIFY=${{ vars.TLS_SKIP_VERIFY }} \
            -e DECK_KONNECT_TOKEN=${{ secrets.KONNECT_TOKEN }} \
            -e DECK_KONNECT_CONTROL_PLANE_NAME=${{ vars.KONNECT_CONTROL_PLANE_NAME }} \
            kong/deck gateway diff merged-deck.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: diff-deck
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: merged-deck
      - name: Deploy
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/tmp \
            -w /tmp \
            -e DECK_KONNECT_ADDR=${{ vars.KONNECT_ADDR }} \
            -e DECK_TLS_SKIP_VERIFY=${{ vars.TLS_SKIP_VERIFY }} \
            -e DECK_KONNECT_TOKEN=${{ secrets.KONNECT_TOKEN }} \
            -e DECK_KONNECT_CONTROL_PLANE_NAME=${{ vars.KONNECT_CONTROL_PLANE_NAME }} \
            kong/deck gateway sync merged-deck.yaml

  upload-spec:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Encode YAML file to base64
        id: encode
        run: |
          CONTENT=$(base64 -w0 ${{ github.workspace }}/openapi/openapi.yaml)
      - name: Get Kong version ID
        id: get_version_id
        run: |
          VERSION_ID=$(curl -X GET -s \
            "https://us.api.konghq.com/v2/api-products/a1f7daf3-2423-42ae-b210-2582df55a6af/product-versions" \
            -H "Authorization: Bearer ${{ secrets.KONNECT_TOKEN }}" \
            | jq -r '.data[] | select(.name == "v1") | .id')
      - name: Upload specification to Kong
        run: |
          curl -X POST \
            "https://us.api.konghq.com/v2/api-products/a1f7daf3-2423-42ae-b210-2582df55a6af/product-versions/${{ steps.get_version_id.outputs.version_id }}/specifications" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.KONNECT_TOKEN }}" \
            -d '{
              "name": "openapi.yaml",
              "content": "'"${{ steps.encode.outputs.content }}"'"
            }'